### PR TITLE
added auth state listener to directly navigate to home when logged in

### PR DESCRIPTION
**Pull request by Basler182**
# *auth state listener*

## :recycle: Current situation & Problem
#37 

## :gear: Release Notes 

- added auth state listener to directly navigate to home when logged in

## :pencil: Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md):
- [x] I agree to follow the [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by PSchmiedmayer — COMMENTED** [review]
Thank you for working on this @Basler182; I would defer to @eldcn and @pauljohanneskraft for a detailed review 👍

**Comment by Basler182** [comment]
> Thank you for working on this @Basler182; I would defer to @eldcn and @pauljohanneskraft for a detailed review 👍

i spoke to @eldcn earlier. he is working on the changes we discussed on tuesday and is removing the firebase auth module from the app. he will then merge the changes into this branch and then we can merge everything together into the master 🚀

**Comment by PSchmiedmayer** [comment]
Sounds great; thank you @Basler182 and @eldcn!

**Comment by eldcn** [comment]
@Basler182, @PSchmiedmayer , @pauljohanneskraft I just opened #55 pointing to this branch 🙌

**Review by PSchmiedmayer — COMMENTED** [review]
Thank you @eldcn for the improvements and working on this feature!

Feel free to sync merging this PR with @Basler182 to get this PR merged; thanks to the two of you to get this in place 🚀

**Review by eldcn — APPROVED** [review]

**Pull request merged**
