### PR TITLE
Adds Android FHIR SDK for data capture

### PR DESCRIPTION
**Pull request by vishnuravi**
# Adds Android FHIR SDK for data capture

## :gear: Release Notes 
This PR adds the Android FHIR SDK's data capture module which provides functionality for rendering FHIR Questionnaires and FHIR data types for HealthConnectOnFHIR.

## :pencil: Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md):
- [X] I agree to follow the [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by PSchmiedmayer** [comment]
Thank you for the additions here @vishnuravi & @Basler182!
As far as I can interpret the log we are still failing with the same coverage report failure due to the large file transformation.

It might make sense to still merge this into messages and then follow the approach that @eldcn proposed to at least temporarily disable coverage reports for the main app target and then investigate this in a smaller and separate PR?

**Review by PSchmiedmayer — COMMENTED** [review]
Thank you for the additions here @vishnuravi & @Basler182!

Not quite sure why the diff is so large; shouldn't this just be a small addition to feature/messages?

Independent of that: As far as I can interpret the log we are still failing with the same coverage report failure due to the large file transformation.

It might make sense to still merge this into messages and then follow the approach that @eldcn proposed to at least temporarily disable coverage reports for the main app target and then investigate this in a smaller and separate PR?

**Comment by eldcn** [comment]
> Not quite sure why the diff is so large; shouldn't this just be a small addition to feature/messages?

I noticed that this branch has been created from main in later state compared to `feature/save-measurements`. I just pushed the needed changes in #53 directly at this [commit](https://github.com/StanfordSpezi/SpeziKt/pull/53/commits/ee0388c923086e22dc2ff7db40f6e3341a366e73), we can observe next if the jacocco issue get's resolved (then we can close this PR in favor of #53). If not, we can temporarily disable coverage report and address in a smaller follow up. CC: @PSchmiedmayer @vishnuravi @Basler182

**Comment by PSchmiedmayer** [comment]
Thank you @eldcn for the context!

**Pull request closed without merging**
